### ISSUE TITLE
take 2 positional argument but 3 were given

### ISSUE THREAD

**Issue by HankIC** [epfl-vlsc/bitfiltrator#1]
hello, I follow the readme"python3 src/create_device_summary.py xcu200-fsgd2104-2-e <working-dir> <xcu200_summary.json>" and input the instruction like the pic bellow, and I get this error. How to make it work???
![image](https://user-images.githubusercontent.com/110684722/228239325-dde03a94-7ac2-4034-b353-a323e7ec0ab6.png)

**Comment by sahandKashani** [comment]
Hi,

Thanks for reporting this bug. I didn't experience it as I was always running experiments in batch using `run_all.py` (instead of explicitly with `create_device_summary.py`), which calls the function correctly.

I've pushed a fix. You can pull the repository and retry. The command should look like this:

```bash
python3 src/create_device_summary.py <part> ~/tmp_working_dir <part>_device_info.json
```

Note that the working directory should not be in the `resources/` directory. You should use a directory outside the git repository. The `run_all.py` file automatically copies the final results of all scripts to the `resources/` directory, but since you are explicitly calling `create_device_summary.py`, you'll have to copy final JSON files to the `resources/` directory yourself afterwards.
