### ISSUE TITLE
can't generate parts_webpack.json

### ISSUE THREAD

**Issue by ghyghy123** [epfl-vlsc/bitfiltrator#3]
Hello, sorry to bother you again, I can't generate parts_webpack.json file when running run_all.py file, and when running create_device_summary, the keyerror "BramRegLoc" appears, can you guide me? Thank you very much

![image](https://user-images.githubusercontent.com/58417169/229740827-d2a89bfe-d0c4-4744-b46e-e97fc0bee70f.png)

**Comment by sahandKashani** [comment]
I think what is happening is that the `parts_webpack.json` file is not being generated (first error message). This in turn causes the rest of the program to crash as it actually reads that json file to continue. If intermediate files that contain data (including the `BramRegLoc` key) are not being generated, then the program crashing is expected.

You need to figure out why the `parts_webpack.json` file fails generation. It is likely due to a command in `src/tcl/get_parts.tcl` not existing in your version of Vivado (which is older than the version I am using based on your prior GitHub issue).

You could try to run the the first Vivado command that is printed in the terminal yourself to see what it outputs?

`vivado -mode batch -source /home/bitfiltrator-main/src/tcl/get_parts.tcl -notrace -tclargs -keep_webpack_only .*ultrascale.* /home/bitfiltrator-main/resources/parts_webpack.json`

**Comment by ghyghy123** [comment]
Thank you, testing can now be completed by changing the version of Vivado. I have another question, how to determine the specific position of the frame address in the bitstream?

**Comment by sahandKashani** [comment]
Hi,

Do you mean the byte-level offset of a specific frame in the entire bitstream (including the bitstream header)?

If yes, you can indirectly get this information using the `extract_frames()` function in `bitstream_state_checker.py`:
https://github.com/epfl-vlsc/bitfiltrator/blob/main/src/bitstream_state_checker.py#L15-L34

The method works for only full bitstreams. It links all `(slrName, FrameAddressRegister)` tuples with a `ConfigFrame` object. A `ConfigFrame` contains a `byte_ofst` member which contains the address of the frame in the full bitstream. You can print this information out to get what you are looking for.

**Comment by sahandKashani** [comment]
Hi,

I realized multiple people may want to know the position of a frame in the bitstream. I updated the [demo.py](https://github.com/epfl-vlsc/bitfiltrator/blob/main/src/demo.py) file to print out this information. The README has also been updated with an example that shows the output.

I hope this helps.

**Comment by ghyghy123** [comment]
Thank you very much. I have a clear understanding
